### ISSUE TITLE
Should fail catastrophically on a failed download

### ISSUE THREAD

**Issue by davidbanham** [Prismatik/cloudinary-migrate#1]
At the moment, if a file fails to download, an error is printed to stderr and the process continues working. It would be easy for a user to fail to see this error and assume that the process had successfully downloaded all files. I think it should throw and exit immediately on error.

**Comment by Nicktho** [comment]
Hmm, I need help triggering this error but from what I can see it should halt the promise sequence and then just exit since its the last call in the file? 

```
fetchImages(opts)
    .then(downloadImages.bind(this, savePath))
    .catch(function(err) { console.error("error: ", err); });
```

**Comment by Nicktho** [comment]
also if we started using babel across our projects we could write 

```
fetchImages(opts)
    .then((images) => downloadImages(images, savePath))
    .catch((err) => console.error("error: ", err));
```

**Comment by Nicktho** [comment]
(we could also probably\* write that now too)

*depending on our io/node version were running locally
